export const modelParts = [
  {
    _id: 'sm_h_1',
    name: 'Space Marine Helmet',
    type: 'head',
    group: 'spaceMarine',
    position: [0, 0, 0],
    scale: [0, 0, 0],
    rotation: [0, 0, 0],
  },
  {
    _id: 'pr_h_1',
    name: 'Primaris Helmet',
    type: 'head',
    group: 'primaris',
    position: [0, 0, 0],
    scale: [0, 0, 0],
    rotation: [0, 0, 0],
  },
  {
    _id: 'sm_t_1',
    name: 'Space Marine Torso',
    type: 'torso',
    group: 'spaceMarine',
    position: [0, 0, 0],
    scale: [0, 0, 0],
    rotation: [0, 0, 0],
  },
  {
    _id: 'pr_t_1',
    name: 'Primaris Torso',
    type: 'torso',
    group: 'primaris',
    position: [0, 0, 0],
    scale: [0, 0, 0],
    rotation: [0, 0, 0],
  },
];
